/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Service = IDL.Variant({
  'studyAbroad' : IDL.Null,
  'jobPlacement' : IDL.Null,
  'ieltsTraining' : IDL.Null,
  'shortTermCourses' : IDL.Null,
  'onlineCourses' : IDL.Null,
});
export const Time = IDL.Int;
export const Enquiry = IDL.Record({
  'id' : IDL.Principal,
  'service' : Service,
  'country' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSubscriber' : IDL.Func([IDL.Text], [], []),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getAllEnquiriesSortedByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(Enquiry)],
      ['query'],
    ),
  'getAllSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Service, IDL.Text, IDL.Text],
      [IDL.Principal],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Service = IDL.Variant({
    'studyAbroad' : IDL.Null,
    'jobPlacement' : IDL.Null,
    'ieltsTraining' : IDL.Null,
    'shortTermCourses' : IDL.Null,
    'onlineCourses' : IDL.Null,
  });
  const Time = IDL.Int;
  const Enquiry = IDL.Record({
    'id' : IDL.Principal,
    'service' : Service,
    'country' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addSubscriber' : IDL.Func([IDL.Text], [], []),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getAllEnquiriesSortedByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(Enquiry)],
        ['query'],
      ),
    'getAllSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Service, IDL.Text, IDL.Text],
        [IDL.Principal],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };