/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Enquiry {
    id: Principal;
    service: Service;
    country: string;
    fullName: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export enum Service {
    studyAbroad = "studyAbroad",
    jobPlacement = "jobPlacement",
    ieltsTraining = "ieltsTraining",
    shortTermCourses = "shortTermCourses",
    onlineCourses = "onlineCourses"
}
export interface backendInterface {
    addSubscriber(email: string): Promise<void>;
    getAllEnquiries(): Promise<Array<Enquiry>>;
    getAllEnquiriesSortedByTimestamp(): Promise<Array<Enquiry>>;
    getAllSubscribers(): Promise<Array<string>>;
    submitEnquiry(fullName: string, phone: string, email: string, service: Service, country: string, message: string): Promise<Principal>;
}
import type { Enquiry as _Enquiry, Service as _Service, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addSubscriber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubscriber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubscriber(arg0);
            return result;
        }
    }
    async getAllEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiries();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiries();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEnquiriesSortedByTimestamp(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEnquiriesSortedByTimestamp();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEnquiriesSortedByTimestamp();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubscribers(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscribers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscribers();
            return result;
        }
    }
    async submitEnquiry(arg0: string, arg1: string, arg2: string, arg3: Service, arg4: string, arg5: string): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(arg0, arg1, arg2, to_candid_Service_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(arg0, arg1, arg2, to_candid_Service_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
}
function from_candid_Enquiry_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    service: _Service;
    country: string;
    fullName: string;
    email: string;
    message: string;
    timestamp: _Time;
    phone: string;
}): {
    id: Principal;
    service: Service;
    country: string;
    fullName: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
} {
    return {
        id: value.id,
        service: from_candid_Service_n4(_uploadFile, _downloadFile, value.service),
        country: value.country,
        fullName: value.fullName,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp,
        phone: value.phone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studyAbroad: null;
} | {
    jobPlacement: null;
} | {
    ieltsTraining: null;
} | {
    shortTermCourses: null;
} | {
    onlineCourses: null;
}): Service {
    return "studyAbroad" in value ? Service.studyAbroad : "jobPlacement" in value ? Service.jobPlacement : "ieltsTraining" in value ? Service.ieltsTraining : "shortTermCourses" in value ? Service.shortTermCourses : "onlineCourses" in value ? Service.onlineCourses : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Service_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): {
    studyAbroad: null;
} | {
    jobPlacement: null;
} | {
    ieltsTraining: null;
} | {
    shortTermCourses: null;
} | {
    onlineCourses: null;
} {
    return value == Service.studyAbroad ? {
        studyAbroad: null
    } : value == Service.jobPlacement ? {
        jobPlacement: null
    } : value == Service.ieltsTraining ? {
        ieltsTraining: null
    } : value == Service.shortTermCourses ? {
        shortTermCourses: null
    } : value == Service.onlineCourses ? {
        onlineCourses: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
